# Параметры данных
data:
  train_csv: "data/train.csv"
  classes_csv: "data/classes.csv"
  train_img_dir: "data/train_256"
  test_img_dir: "data/test_256"
  image_size: 256
  batch_size: 24
  val_size: 0.25
  num_workers: 0
  stratify: false
  random_state: 42

# Параметры модели
model:
  architecture: 'polonskaya_model'
  num_classes: 46
  dropout: 0.5

# Параметры обучения
training:
  epochs: 50
  lr: 0.001
  weight_decay: 0.002
  max_patience: 5
  model_save_path: "model_best.pth"  # Путь сохранения модели
  loss_function: "CrossEntropyLoss"  # Функция потерь
  factor: 0.6  # Фактор уменьшения LR
  scheduler_patience: 2  # Патенция для LR scheduler
  scheduler_mode: "min"  # Режим ReduceLROnPlateau: "min" или "max"

# Устройство (cuda или cpu)
device: "cuda"
